### ISSUE TITLE
Send notification to remaining members when last owner disappears

### ISSUE THREAD

**Issue by mortenlj** [nais/teams-backend#146]
When the last owner of a team is removed, a proactive notification to the remaining members about the situation would do wonders.

Options:
- Slack notification to team channels as defined in Teams
- Slack notification to each remaining team member
- Email to each remaining team member
- Combination of the above

**Comment by mortenlj** [comment]
https://nav-it.slack.com/archives/C5KUST8N6/p1692178712752459

**Comment by jksolbakken** [comment]
The backend bit ended up living in the "NAIS Teams slackbot". Also restricted the ability to delete the last owner in the frontend.
